<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\AkunAAS; // Sesuaikan jika nama Model Anda berbeda

class AkunAASSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Opsional: Menonaktifkan proteksi Mass Assignment jika menggunakan Model Eloquent
        // AkunAAS::unguard(); 

        $data = [
            [
                'id' => 2,
                'kode_aas' => '5010001506',
                'nama_aas' => 'Perlengkapan Masjid',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 3,
                'kode_aas' => '5010001507',
                'nama_aas' => 'Perlengkapan Kantor',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 5,
                'kode_aas' => '5010002504',
                'nama_aas' => 'Iuran-iuran',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 6,
                'kode_aas' => '5010002506',
                'nama_aas' => 'Rapat-rapat / Raker',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 7,
                'kode_aas' => '5010002507',
                'nama_aas' => 'Transpor Dinas',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 8,
                'kode_aas' => '5010002508',
                'nama_aas' => 'Konsumsi',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 9,
                'kode_aas' => '5010002512',
                'nama_aas' => 'Sumbangan - sumbangan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 10,
                'kode_aas' => '5010002513',
                'nama_aas' => 'Dokumentasi & Informasi',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 11,
                'kode_aas' => '5010002514',
                'nama_aas' => 'Bensin/Tol/Parkir/Kendaraan Dinas',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 12,
                'kode_aas' => '5010002517',
                'nama_aas' => 'Lain-lain Keperluan Kantor',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 13,
                'kode_aas' => '5010003505',
                'nama_aas' => 'Insentif / Bonus',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 14,
                'kode_aas' => '5010003514',
                'nama_aas' => 'Bantuan Karyawan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 15,
                'kode_aas' => '5010005501',
                'nama_aas' => 'Pemeliharaan Gedung / Bangunan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 16,
                'kode_aas' => '5010005502',
                'nama_aas' => 'Pemeliharaan Emplasement',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 19,
                'kode_aas' => '5010001504',
                'nama_aas' => 'Perlengkapan Kebersihan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 88,
                'kode_aas' => '1111111111',
                'nama_aas' => 'Pembentukan Kas Kecil',
                'status' => 'k',
                'kategori' => 'pembentukan',
            ],
            [
                'id' => 89,
                'kode_aas' => '1111111112',
                'nama_aas' => 'Pengisian Kas Kecil',
                'status' => 'k',
                'kategori' => 'pengisian',
            ],
            [
                'id' => 105,
                'kode_aas' => '5010001501',
                'nama_aas' => 'Perlengkapan ATK',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 106,
                'kode_aas' => '5010001502',
                'nama_aas' => 'Pelengkapan Cetakan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 107,
                'kode_aas' => '5010001503',
                'nama_aas' => 'Perlengkapan Komputer/Foto Copy',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 109,
                'kode_aas' => '5010002502',
                'nama_aas' => 'Jamuan Tamu',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 110,
                'kode_aas' => '5010002501',
                'nama_aas' => 'Listrik/Telp/Air/Gas',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 111,
                'kode_aas' => '5010002505',
                'nama_aas' => 'Supervisi/Audit/Konsultasi',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 112,
                'kode_aas' => '5010002509',
                'nama_aas' => 'Pos/Paket/Kurir',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 113,
                'kode_aas' => '5010002510',
                'nama_aas' => 'Surat Kabar/Majalah/Buletin',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 114,
                'kode_aas' => '5010002511',
                'nama_aas' => 'Sumbangan Kepada Lembaga',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 115,
                'kode_aas' => '5010002515',
                'nama_aas' => 'IT MAA',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 116,
                'kode_aas' => '5010002516',
                'nama_aas' => 'Keperluan Kursus',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 117,
                'kode_aas' => '5010003501',
                'nama_aas' => 'Gaji/Honor/Nafkah',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 118,
                'kode_aas' => '5010003502',
                'nama_aas' => 'Uang Kerajinan Kerja (UKK)',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 119,
                'kode_aas' => '5010003503',
                'nama_aas' => 'Transpor',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 120,
                'kode_aas' => '5010003504',
                'nama_aas' => 'Lembur',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 122,
                'kode_aas' => '5010003506',
                'nama_aas' => 'Tunjangan Pengobatan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 123,
                'kode_aas' => '5010003507',
                'nama_aas' => 'Tunjangan Hari Raya (THR)',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 124,
                'kode_aas' => '5010003508',
                'nama_aas' => 'Tunjangan PPh21',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 125,
                'kode_aas' => '5010003509',
                'nama_aas' => 'Jaminan Hari Tua (Pensiun)',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 126,
                'kode_aas' => '5010003510',
                'nama_aas' => 'Tunjangan Cuti',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 127,
                'kode_aas' => '5010003511',
                'nama_aas' => 'Uang Makan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 128,
                'kode_aas' => '5010003512',
                'nama_aas' => 'Jasa Pengabdian/ Pesangon',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 129,
                'kode_aas' => '5010003513',
                'nama_aas' => 'Pakaian Seragam',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 130,
                'kode_aas' => '5010003514',
                'nama_aas' => 'Bantuan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 131,
                'kode_aas' => '5010003515',
                'nama_aas' => 'Haji',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 132,
                'kode_aas' => '5010003516',
                'nama_aas' => 'Pensiun',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 133,
                'kode_aas' => '5010003517',
                'nama_aas' => 'Rekreasi',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 134,
                'kode_aas' => '5010003518',
                'nama_aas' => 'Tunjangan Kematian',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 135,
                'kode_aas' => '5010004501',
                'nama_aas' => 'Studi Banding',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 136,
                'kode_aas' => '5010004502',
                'nama_aas' => 'Seminar',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 137,
                'kode_aas' => '5010004503',
                'nama_aas' => 'Pembinaan Karyawan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 138,
                'kode_aas' => '5010005503',
                'nama_aas' => 'Pemeliharaan Instalasi',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 139,
                'kode_aas' => '5010005504',
                'nama_aas' => 'Pemeliharaan Alat Kantor',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 140,
                'kode_aas' => '5010005505',
                'nama_aas' => 'Pemeliharaan Peralatan Masjid',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 141,
                'kode_aas' => '5010005506',
                'nama_aas' => 'Pemeliharaan Kendaraan Dinas',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 142,
                'kode_aas' => '5010005507',
                'nama_aas' => 'Pemeliharaan Tempat Wudhu',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 143,
                'kode_aas' => '5010005508',
                'nama_aas' => 'Pemeliharaan Aula',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 144,
                'kode_aas' => '5010005509',
                'nama_aas' => 'Pemeliharaan Ruang Kursus',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 145,
                'kode_aas' => '5010005510',
                'nama_aas' => 'Pemeliharaan Genset',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 146,
                'kode_aas' => '5010006501',
                'nama_aas' => 'Penyusutan Gedung/ Bangunan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 147,
                'kode_aas' => '5010006502',
                'nama_aas' => 'Penyusutan Instalasi',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 148,
                'kode_aas' => '5010006503',
                'nama_aas' => 'Penyusutan Emplasment',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 149,
                'kode_aas' => '5010006504',
                'nama_aas' => 'Pemeliharaan Inventaris',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 150,
                'kode_aas' => '5010006505',
                'nama_aas' => 'Penyusutan Kendaraan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 151,
                'kode_aas' => '5020401501',
                'nama_aas' => 'Kegiatan Ramadhan & Iedul Fitri',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 152,
                'kode_aas' => '5020401502',
                'nama_aas' => 'Kegiatan Iedul Fitri',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 153,
                'kode_aas' => '5020401503',
                'nama_aas' => 'Isra Miraj',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 154,
                'kode_aas' => '5020401504',
                'nama_aas' => 'Maulid Nabi',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 155,
                'kode_aas' => '5020401505',
                'nama_aas' => 'Muharram',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 156,
                'kode_aas' => '5020401506',
                'nama_aas' => 'Kegiatan Taklim',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 157,
                'kode_aas' => '5020401507',
                'nama_aas' => 'Kegiatan Pengajian',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 158,
                'kode_aas' => '5020401508',
                'nama_aas' => 'Kegoatan Pengajian',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 159,
                'kode_aas' => '5020402501',
                'nama_aas' => 'Honor Khatib/Imam/Muadzin',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 160,
                'kode_aas' => '5020402502',
                'nama_aas' => 'Konsusmi Jumat',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 161,
                'kode_aas' => '5020402503',
                'nama_aas' => 'Buletin Jumat',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 162,
                'kode_aas' => '5020402504',
                'nama_aas' => 'Insentif Jumat',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 163,
                'kode_aas' => '5020402505',
                'nama_aas' => 'Penerbitan Kumpulan Buletin',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 164,
                'kode_aas' => '5020402506',
                'nama_aas' => 'Penulisan Buletin',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 165,
                'kode_aas' => '5020404501',
                'nama_aas' => 'Sumbangan Kepada Lembaga',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 166,
                'kode_aas' => '5020404502',
                'nama_aas' => 'Sumbangan Kepada Perorangan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 167,
                'kode_aas' => '5020404503',
                'nama_aas' => 'Sumbangan Kepada Lembaga',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 168,
                'kode_aas' => '5020404504',
                'nama_aas' => 'Sumbangan Kepada Perorangan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 169,
                'kode_aas' => '5020404505',
                'nama_aas' => 'Subsidi Majelis Taklim',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 170,
                'kode_aas' => '5020404506',
                'nama_aas' => 'PengIslaman',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 171,
                'kode_aas' => '5020404507',
                'nama_aas' => 'Honor Guru/ Karyawan Kursus',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 172,
                'kode_aas' => '5020404508',
                'nama_aas' => 'Honor Pengurus dan Guru LTA',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 173,
                'kode_aas' => '5020405501',
                'nama_aas' => 'Biaya Kegiatan Aula',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 174,
                'kode_aas' => '5020405502',
                'nama_aas' => 'Biaya Kegiatan Qultum',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 175,
                'kode_aas' => '5020405503',
                'nama_aas' => 'Biaya Kegiatan Masjid Lainnya',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 176,
                'kode_aas' => '5020405504',
                'nama_aas' => 'Biaya Kegiatan Wakala Dinar Dirham',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 177,
                'kode_aas' => '5020406501',
                'nama_aas' => 'Penggantian Uang Transpor',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 178,
                'kode_aas' => '5020406502',
                'nama_aas' => 'Bantuan/ Hadiah Pengurus Takmir',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 179,
                'kode_aas' => '5060001501',
                'nama_aas' => 'Beban Adm. Giro bank',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 180,
                'kode_aas' => '5060002502',
                'nama_aas' => 'Beban Adm. Deposito',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 181,
                'kode_aas' => '5060005501',
                'nama_aas' => 'Selisih Kas',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 182,
                'kode_aas' => '5060005502',
                'nama_aas' => 'Rugi Penjualan Aktiva',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 183,
                'kode_aas' => '5060005503',
                'nama_aas' => 'Biaya Lainnya',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 184,
                'kode_aas' => '5060005504',
                'nama_aas' => 'Biya',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 185,
                'kode_aas' => '5060006501',
                'nama_aas' => 'Beban Adm. Tabungan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 186,
                'kode_aas' => '5010001505',
                'nama_aas' => 'Perlengkapan Kesehatan',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 187,
                'kode_aas' => '5010002503',
                'nama_aas' => 'Foto Copy',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 188,
                'kode_aas' => '5010005510',
                'nama_aas' => 'Pemeliharaan Genset',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 189,
                'kode_aas' => '2070010523',
                'nama_aas' => 'Bantuan Ibnu Sabil',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
            [
                'id' => 190,
                'kode_aas' => '2070010508',
                'nama_aas' => 'Bantuan Fisabilillah',
                'status' => 'd',
                'kategori' => 'pengeluaran',
            ],
        ];

        // Memasukkan data ke tabel menggunakan Query Builder
        DB::table('akun_aas')->insert($data);

        // Opsional: Mengembalikan proteksi Mass Assignment
        // AkunAAS::reguard(); 
    }
}
